"""
layout.py

Shared binary layout for EOS Event Schema v1.
These values MUST match the MQL5 structs exactly.
"""

# ---------- Struct Sizes ----------

EVENT_METADATA_SIZE = 384
TICK_EVENT_SIZE = 428

# ---------- Metadata Offsets ----------

OFFSET_EVENT_ID = 0
LEN_EVENT_ID = 64

OFFSET_EVENT_TYPE = 64
OFFSET_DOMAIN = 66
OFFSET_SCHEMA_MAJOR = 68
OFFSET_SCHEMA_MINOR = 70

OFFSET_EXCHANGE_TIME = 72
OFFSET_LOCAL_TIME = 80
OFFSET_MONOTONIC = 88

OFFSET_PRODUCER = 96
LEN_PRODUCER = 32

OFFSET_SESSION = 128
LEN_SESSION = 64

OFFSET_SYMBOL = 192
LEN_SYMBOL = 12

OFFSET_PARENT1 = 204
LEN_PARENT1 = 64

OFFSET_PARENT2 = 268
LEN_PARENT2 = 64

OFFSET_ALGORITHM = 332
LEN_ALGORITHM = 32

OFFSET_ALGO_VERSION = 364
LEN_ALGO_VERSION = 16

OFFSET_CHECKSUM = 380

# ---------- Payload ----------

PAYLOAD_OFFSET = EVENT_METADATA_SIZE
